import type { Metadata } from "next";

import { WalletStatusBar } from "@/components/wallet-status-bar";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
  title: "Privacy Policy - Ethereum Escrow",
  description:
    "Privacy policy for the Ethereum Escrow dApp, including wallet data, local storage, and assistant processing.",
};

const LAST_UPDATED = "April 20, 2026";

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <WalletStatusBar />
      <main className="container mx-auto max-w-4xl space-y-8 px-4 py-10">
        <header className="space-y-3">
          <h1 className="font-heading text-3xl font-semibold tracking-tight sm:text-4xl">
            Privacy Policy
          </h1>
          <p className="text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>
          <p className="text-sm leading-relaxed text-muted-foreground">
            This page explains what data this dApp handles, where that data is stored, and how it
            is used when you interact with escrow flows and the AI assistant.
          </p>
        </header>

        <Separator />

        <section className="grid gap-4">
          <Card>
            <CardHeader>
              <CardTitle>1. Service scope</CardTitle>
            </CardHeader>
            <CardContent className="text-sm leading-relaxed text-muted-foreground">
              Ethereum Escrow is a frontend decentralized application. Contract state and
              transactions live on public blockchain networks (Sepolia or local Hardhat in
              development). We do not custody user funds on our servers.
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>2. Wallet and on-chain data</CardTitle>
            </CardHeader>
            <CardContent className="text-sm leading-relaxed text-muted-foreground">
              When you connect your wallet, your public wallet address and selected network are used
              in your browser to interact with contracts. Blockchain transactions are public by
              nature and can be viewed by anyone through block explorers.
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>3. Local browser storage</CardTitle>
            </CardHeader>
            <CardContent className="text-sm leading-relaxed text-muted-foreground">
              The AI assistant stores limited chat history in your browser localStorage to improve
              continuity between visits. A first-visit loading/prefetch flag is stored in
              sessionStorage. You can clear both by clearing site storage in your browser settings.
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>4. AI assistant processing</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2 text-sm leading-relaxed text-muted-foreground">
              <p>
                Messages you send to the assistant are processed by this app&apos;s backend endpoint
                and then sent to a third-party model provider (Groq) to generate responses.
              </p>
              <p>
                Guardrails are used to reduce unsafe inputs, including attempts to share secrets
                (such as seed phrases or private keys). Do not enter private keys, seed phrases, or
                wallet backups.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>5. Cookies and analytics</CardTitle>
            </CardHeader>
            <CardContent className="text-sm leading-relaxed text-muted-foreground">
              This app does not rely on analytics cookies for core escrow functionality. Standard
              browser/network logs may still be generated by hosting infrastructure for security and
              reliability.
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>6. Your choices and rights</CardTitle>
            </CardHeader>
            <CardContent className="text-sm leading-relaxed text-muted-foreground">
              You can disconnect your wallet at any time and clear local browser storage. If you
              have questions about this policy, contact the project maintainers through the
              repository issue tracker.
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>7. Policy updates</CardTitle>
            </CardHeader>
            <CardContent className="text-sm leading-relaxed text-muted-foreground">
              We may update this policy as the product evolves. The date at the top of this page
              reflects the latest revision.
            </CardContent>
          </Card>
        </section>
      </main>
    </div>
  );
}
